//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalRightsManagement.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigitalRightsManagement.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities should not define their own parameterless constructors as they are generated automatically..
        /// </summary>
        internal static string EntityConstructorAnalyzerDescription {
            get {
                return ResourceManager.GetString("EntityConstructorAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity &apos;{0}&apos; must not define its own parameterless constructor - it will be generated automatically.
        /// </summary>
        internal static string EntityConstructorAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("EntityConstructorAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity must use source-generated parameterless constructor.
        /// </summary>
        internal static string EntityConstructorAnalyzerTitle {
            get {
                return ResourceManager.GetString("EntityConstructorAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities should be created using parameterized constructors to ensure proper initialization..
        /// </summary>
        internal static string EntityInstantiationAnalyzerDescription {
            get {
                return ResourceManager.GetString("EntityInstantiationAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be instantiated with a parameterized constructor.
        /// </summary>
        internal static string EntityInstantiationAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("EntityInstantiationAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity instantiation must use parameterized constructor.
        /// </summary>
        internal static string EntityInstantiationAnalyzerTitle {
            get {
                return ResourceManager.GetString("EntityInstantiationAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All classes that inherit from Entity must be marked as partial..
        /// </summary>
        internal static string EntityPartialAnalyzerDescription {
            get {
                return ResourceManager.GetString("EntityPartialAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class &apos;{0}&apos; inherits from Entity and must be partial.
        /// </summary>
        internal static string EntityPartialAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("EntityPartialAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes inheriting from Entity must be partial.
        /// </summary>
        internal static string EntityPartialAnalyzerTitle {
            get {
                return ResourceManager.GetString("EntityPartialAnalyzerTitle", resourceCulture);
            }
        }
    }
}
