name: .NET

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"

  pull_request:
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    permissions:
      pull-requests: write

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      DOTNET_MULTILEVEL_LOOKUP: false
      DOTNET_INSTALL_DIR: ${{ matrix.os == 'ubuntu-latest' && '' || 'dotnet' }}
      ASPIRE_ALLOW_UNSECURED_TRANSPORT: true
      SuppressNETCoreSdkPreviewMessage: true

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Print .NET info
      run: dotnet --info

    - name: Install & trust dev-certs
      id: install-dev-certs
      if: matrix.os == 'ubuntu-latest'
      run: dotnet dev-certs https --trust

    - name: Restore local tools
      run: dotnet tool restore

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      id: test
      if: matrix.os == 'ubuntu-latest'
      run: >
        dotnet test
        --no-build --verbosity normal
        --collect:"XPlat Code Coverage" --settings CodeCoverage.runsettings
        --logger console --logger trx --logger html
        --results-directory coverage
        --blame
        --
        RunConfiguration.CollectSourceInformation=true

    - name: Merge coverage files
      if: matrix.os == 'ubuntu-latest'
      run: |
        dotnet reportgenerator \
          -reports:"coverage/**/*.cobertura.xml" \
          -targetdir:"coverage/merged" \
          -reporttypes:"Html;Cobertura"

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      if: matrix.os == 'ubuntu-latest'
      with:
        filename: coverage/merged/Cobertura.xml
        badge: true
        format: 'markdown'
        output: 'both'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request' && matrix.os == 'ubuntu-latest'
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Upload code coverage results artifact
      uses: actions/upload-artifact@v4
      if: matrix.os == 'ubuntu-latest'
      with:
        name: code-coverage-results
        path: code-coverage-results.md
        retention-days: 1

    - name: Write to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
      if: matrix.os == 'ubuntu-latest'
