namespace DigitalRightsManagement.SourceGenerators;

/// <summary>
/// Provides utilities for source generators.
/// </summary>
public static class SourceGeneratorUtilities
{
    /// <summary>
    /// Returns the standard header for generated files.
    /// </summary>
    /// <param name="typeName">The name of the type being generated.</param>
    public static string GetGeneratedHeader(string typeName) => $"""
                                                                 // <auto-generated/>
                                                                 #nullable enable
                                                                 #pragma warning disable CS1591 // Missing XML comment for publicly visible type or member '{typeName}'
                                                                 #pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor
                                                                 """;
}
