using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace DigitalRightsManagement.SourceGenerators;

/// <summary>
/// A source generator that generates the ValueObject attribute.
/// </summary>
[Generator]
public sealed class ValueObjectAttributeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context) => context.RegisterPostInitializationOutput(GenerateValueObjectAttribute);

    private static void GenerateValueObjectAttribute(IncrementalGeneratorPostInitializationContext context)
    {
        context.AddSource("ValueObjectAttribute.g.cs", SourceText.From(GenerateAttributeSource, Encoding.UTF8));
    }

    private const string GenerateAttributeSource =
        """
        // <auto-generated/>
        #nullable enable
        #pragma warning disable CS1591 // Missing XML comment for publicly visible type or member ...
        #pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor

        namespace DigitalRightsManagement.Common.DDD;

        [System.AttributeUsage(System.AttributeTargets.Struct)]
        public sealed class ValueObjectAttribute<T> : System.Attribute where T : notnull
        {
            public string? ErrorNamespace { get; init; }
        }
        """;
}
