using Microsoft.CodeAnalysis;

namespace DigitalRightsManagement.SourceGenerators
{
    [Generator]
    public sealed class ValueObjectAttributeGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(GenerateAttributes);
        }

        private static void GenerateAttributes(IncrementalGeneratorPostInitializationContext context)
        {
            const string source = """
                                  // <auto-generated/>
                                  #nullable enable
                                  #pragma warning disable CS1591 // Missing XML comment for publicly visible type or member ...
                                  #pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor

                                  namespace DigitalRightsManagement.Common.DDD;

                                  [AttributeUsage(AttributeTargets.Struct)]
                                  public sealed class ValueObjectAttribute<T> : System.Attribute where T : notnull
                                  {
                                      public string? ErrorNamespace { get; init; }
                                  }
                                  """;

            context.AddSource($"ValueObjectAttribute.g.cs", source);
        }
    }
}
